### PR TITLE
Add more metadata to extension

### PR DESCRIPTION
**Pull request by iawia002**
~1. Add a default language option~
  * Screenshot 2023-06-07 at 17 50 08
2. Add static file directory configuration, requiring all static files to be stored in this directory
3. Add extension provider configuration

ref https://github.com/kubesphere/issues/issues/1024 https://github.com/kubesphere/issues/issues/1097

### CODE REVIEW

**Review by stoneshi-yunify — COMMENTED** [review]
others look good to me

**Comment by stoneshi-yunify** [comment]
you may also provide a `Validate` func, to verify if a given file is a extension package, like the helm validate command.

**Comment by iawia002** [comment]
> you may also provide a `Validate` func, to verify if a given file is a extension package, like the helm validate command.

I have provided this function as well, the validation steps will be gradually improved.

/cc @wansir @stoneshi-yunify

**Review by stoneshi-yunify — APPROVED** [review]
/lgtm

**Comment by wansir** [comment]
LGTM

**Pull request merged**
